[versions]
kotlin = "1.8.20"
kotlinx-coroutines = "1.7.2"
kotlinx-serialization = "1.6.0"
dagger = "2.46.1"

android-gradle-plugin = "8.1.1"
cookpad-lisence-plugin = "1.2.8"

core-ktx = "1.10.1"
activity-ktx = "1.7.2"
fragment-ktx = "1.6.0"
preference-ktx = "1.2.0"
viewmodel-ktx = "2.6.1"

appcompat = "1.6.1"
recyclerview = "1.3.0"
material = "1.9.0"
swiperefreshlayout = "1.1.0"
browser = "1.5.0"
exifinterface = "1.3.6"
multidex = "2.0.1"
installreferrer = "2.2"
constraintlayout = "2.1.4"

okhttp = "4.10.0"
retrofit = "2.9.0"
retrofit-kotlin-serialization-converter = "1.0.0"
mockito = "5.0.0"
robolectric = "4.10.3"
espresso = "3.5.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewmodel-ktx" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.0.0" }

android-material = { module = "com.google.android.material:material", version.ref = "material" }
kotlin-std-lib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version = "32.2.3" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }

okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp-client = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

retrofit-client = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-kotlin-serialization-converter" }

logger = { module = "com.orhanobut:logger", version = "2.2.0" }
stetho = { module = "com.facebook.stetho:stetho-okhttp3", version = "1.6.0" }
eventbus = { module = "org.greenrobot:eventbus", version = "3.2.0" }

#Test
test-junit = { module = "junit:junit", version = "4.13.2" }

test-androidx-test-core-ktx = { module = "androidx.test:core-ktx", version = "1.5.0" }
test-androidx-test-runner = { module = "androidx.test:runner", version = "1.5.2" }
test-androidx-test-rules = { module = "androidx.test:rules", version = "1.5.0" }
test-androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version = "1.1.5" }
test-androidx-core-testing = { module = "androidx.arch.core:core-testing", version = "2.2.0" }
test-androidx-multidex-instrumentation = { module = "androidx.multidex:multidex-instrumentation", version.ref = "multidex" }
test-hamcrest = { module = "org.hamcrest:hamcrest", version = "2.2" }
test-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
test-dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
test-okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver" }

test-mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
test-mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }
test-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }

test-robolectric-client = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-robolectric-shadows-multidex = { module = "org.robolectric:shadows-multidex", version.ref = "robolectric" }

test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
test-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "espresso" }
test-espresso-idling-resource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinx-serialization" }

google-services = { id = "com.google.gms.google-services", version = "4.3.10" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.8.1" }

dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
